version: "3.1"

services:

  mongo1:
    image: mongo
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./data/m1:/data/db
      - ./config/m1:/data/configdb
      - ./log/m1:/data/db/log
      - ./scripts/:/scripts
    environment:
      MONGO_INITDB_DATABASE: admin
      IS_PRIMARY: true
    ports:
      - 50001:50001
    command: bash /scripts/endpoint.sh
