#!/usr/bin/bash

print_head(){
    echo ""
    echo "========================$1========================"
}

check_connection(){
    print_head 'CHECK CONNECTION MONGO1'
    mongosh mongodb://usr:pass@mongo1/admin
}

initrs() {

    if [ "$IS_PRIMARY" != "true" ]
    then
        print_head "NOT_PRIMARY"
        return 1
    fi

    print_head 'PRIMARY SETUP'
    until check_connection
    do
        print_head '!CONNECTION FAIL!'
    done

    print_head 'INIT RS SCRIPT'
    mongosh mongodb://usr:pass@mongo1/admin < /scripts/init.js
    # mongod --keyFile /scripts/mongo-keyfile --bind_ip_all --replSet "my-mongo-set"
}

# INIT RS SCRIPT
initrs > /rs-init.log.txt &

# set key to mongodb
chown mongodb:mongodb /scripts/mongo-keyfile

# START DATABASE
mongod --bind_ip_all







# ????????????????????????????????????????
# mongod --bind_ip_all --replSet "my-mongo-set"
